name: backlog_roulette
description: "A tool for gamers to use to decide their next game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  google_fonts: ^7.0.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  http: ^1.6.0
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  audioplayers: ^6.5.1
  go_router: ^17.0.1
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  carousel_slider: ^5.1.1
  page_transition: ^2.2.1
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/audio/